import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const circularStd = localFont({
  src: "./fonts/CircularStd.ttf",
  variable: "--font-circular-std",
  weight: "100 200 300 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${circularStd.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
